# Max number of lines
set-option -g history-limit 100000

# Change the background color to white
#set -g window-active-style bg=black

# Extending the length of session name
set -g status-left-length 20

# quickly open a new window
bind N new-window

# pane movement shortcuts (same as vim)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# There are some issues with xterm/tmux, leave the mouse to be handled by xterm
# set -g mouse on

#### copy mode : vim ####

# set vi mode for copy mode
setw -g mode-keys vi

# CRTL+k to clean the history
bind -n C-k clear-history
