Mox.defmock(Deployer.MonitorMock, for: Deployer.Monitor.Adapter)
Mox.defmock(Deployer.StatusMock, for: Deployer.Status.Adapter)
Mox.defmock(Deployer.ReleaseMock, for: Deployer.Release.Adapter)
Mox.defmock(Deployer.HotUpgradeMock, for: Deployer.HotUpgrade.Adapter)
Mox.defmock(Deployer.SelfUpgrade.SourceMock, for: Deployer.SelfUpgrade.Source.Adapter)
Mox.defmock(Deployer.SelfUpgrade.ExecutorMock, for: Deployer.SelfUpgrade.Executor.Adapter)
