name: Publishing Testing Releases

on:
  push:
    tags:
      - "*"

env:
  MIX_ENV: prod
  SHELL: /usr/bin/bash

jobs:
  build:
    if: github.event.base_ref != 'refs/heads/main'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        otp: [27, 28]
    env:
      ARTIFACT_NAME: deployex-ubuntu-24.04-otp-${{ matrix.otp }}.tar.gz
    steps:
      - uses: actions/checkout@v7

      - name: Install libcap-dev [recommended by erlexec]
        run: sudo apt-get install libcap-dev -y

      - name: Copy .tool-versions
        run: cp devops/releases/otp-${{ matrix.otp }}/.tool-versions .

      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Install Elixir dependencies
        run: mix do deps.get + compile --warnings-as-errors

      - name: Assets Deploy
        run: mix assets.deploy

      - name: Compile and Generate a Release
        run: mix release

      - name: Rename Artifact
        run: mv _build/prod/*.tar.gz ${{ env.ARTIFACT_NAME }}

      - name: Calculate checksum
        run: sha256sum ${{ env.ARTIFACT_NAME }} > ${{ env.ARTIFACT_NAME }}.sha256

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            ${{ env.ARTIFACT_NAME }}
            ${{ env.ARTIFACT_NAME }}.sha256

  copyInstaller:
    if: github.event.base_ref != 'refs/heads/main'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - name: Prepare installer and checksum
        run: |
          cp devops/installer/deployex.sh .
          sha256sum deployex.sh > deployex.sh.sha256

      - uses: actions/upload-artifact@v4
        with:
          name: deployex.sh
          path: |
            deployex.sh
            deployex.sh.sha256

  upload_aws:
    if: github.event.base_ref != 'refs/heads/main'
    name: Upload files to AWS environment
    needs: [build, copyInstaller]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Download all artefacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Create checksums file
        run: cat *.sha256 > checksum.txt

      - name: Upload artefacts to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: sa-east-1
        run: |
          for file in deployex-ubuntu-24.04-otp-*.tar.gz deployex.sh checksum.txt; do
            aws s3 cp "$file" "s3://${{ secrets.CLOUD_TEST_STORAGE }}"
          done
